


name: Infrastrcuture test & validation

on:
    push:
        branches:
            - dev

jobs:
    check-infrastructure:
        runs-on: ubuntu-24.04

        defaults:
            run:
                working-directory: infrastructure/data_collection_infra
        
        steps:
            - name: clone repo into ubuntu machine
              uses: actions/checkout@v4

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v3 #stores it in a temporary manner
              with:
                aws-access-key-id: ${{secrets.DEVELOPER_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.DEVELOPER_SECRET_ACCESS_KEY}}
                aws-region: ${{secrets.INFRASTRCUTURE_REGION}}

            - name: setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.9.5

            - name: initialize terraform 
              run: terraform init

            - name: format the terraform configuration code
              run: terraform fmt --recursive

            - name: check the syntax of the terraform code
              run: terraform validate

            - name: infrastructure setup logic 
              run: |
                terraform plan \
                  -var="anime_etl_region=${{secrets.INFRASTRCUTURE_REGION}}" \
                  -var="lambda_infra_name=${{secrets.LAMBDA_NAME}}" \
                  -var="s3_data_lake_name=${{secrets.S3_DATA_LAKE}}" \
                  -var="s3_path_to_processed_data_file=${{secrets.S3_KEY_PATH_TO_FILE}}"